### ISSUE TITLE
unhandled promise rejection warning?

### ISSUE THREAD

**Issue by sunflowerIU** [moontai0724/fantia-downloader#3]
UnhandledPromiseRejectionWarning: Error: Request failed with status code 404
    at createError (E:\python notes\fantia-downloader-master\node_modules\axios\lib\core\createError.js:16:15)
    at settle (E:\python notes\fantia-downloader-master\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (E:\python notes\fantia-downloader-master\node_modules\axios\lib\adapters\http.js:269:11)       
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:8964) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async

**Comment by moontai0724** [comment]
Hi sunflowerIU,

This is what I guess:

Seems like the post of id which you given was not exist, so it cannot found the post.
Can you access the post in browser? URL format: `https://fantia.jp/posts/${Post ID}`, like: `https://fantia.jp/posts/123456`.
